name: FPL Radar automatique

on:
  workflow_dispatch:            # toujours possible de lancer à la main
  schedule:
    - cron: "0 10 * * *"        # Tous les jours à 10h UTC

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Génère (ou met à jour) un fichier resume.md pour garantir un commit quotidien
      - name: Générer resume.md (rapport quotidien)
        run: |
          python - << 'PY'
          from datetime import datetime, timezone
          import pathlib, platform
          now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S %Z")
          p = pathlib.Path("resume.md")
          lines = [
              "# Rapport FPL Radar",
              "",
              f"- Généré automatiquement : {now}",
              f"- Runner : {platform.platform()}",
          ]
          p.write_text("\n".join(lines) + "\n", encoding="utf-8")
          print("Écrit :", p.resolve())
          PY

      # Commit ciblé du rapport
      - name: Commit and push resume.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add resume.md
          git commit -m "Update resume.md (auto)" || echo "Nothing to commit"
          git push

      # Commit de tout autre artefact généré (si présent)
      - name: Commit des résultats
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --cached --quiet; then
            echo "Aucun changement à commit."
          else:
            git commit -m "auto: update"
            git push
          fi

      - name: Notification fin de workflow
        run: echo "✅ Workflow terminé avec succès à $(date -u) (UTC)"
