name: FPL Radar automatique

on:
  schedule:
    - cron: '0 6 * * *'   # Tous les jours à 06h00 UTC
  workflow_dispatch:       # Lancer manuellement si besoin

permissions:
  contents: write

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Exécuter main.py
        run: python main.py

      - name: Commit et push des résultats
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add résumé.md || true
          if git diff --cached --quiet; then
            echo "Aucun changement à commit."
          else
            git commit -m "Mise à jour automatique"
            git push
          fi
