name: FPL Radar automatique

on:
  workflow_dispatch:            # lancement manuel possible
  schedule:
    - cron: "0 10 * * *"        # Tous les jours à 10h UTC

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Écrit un contenu FIXE (sans append) pour éviter tout doublon
      - name: Générer resume.md (rapport quotidien, idempotent)
        run: |
          python - << 'PY'
          from datetime import datetime, timezone
          import pathlib, platform, textwrap
          now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S %Z")
          content = textwrap.dedent(f"""\
          # Rapport FPL Radar

          - Généré automatiquement : {now}
          - Runner : {platform.platform()}
          """)
          pathlib.Path("resume.md").write_text(content, encoding="utf-8")
          print("Écrit : resume.md")
          PY

      # Commit ciblé du rapport
      - name: Commit and push resume.md
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add resume.md
          git commit -m "Update resume.md (auto)" || echo "Nothing to commit"
          git push

      # Commit du reste du dépôt (s'il y a d'autres artefacts)
      - name: Commit des résultats (reste du dépôt)
        shell: bash
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "auto: update"
            git push
          else
            echo "Aucun changement à commit."
          fi

      - name: Notification fin de workflow
        run: echo "✅ Workflow terminé avec succès à $(date -u) (UTC)"
